### ISSUE TITLE
Omg

### ISSUE THREAD

**Issue by supadrupa** [BeDjango/bedjango-starter#1]
Is really node_module in repozitory?!
It's the worst code I have ever seen.

**Comment by pydanny** [comment]
This has been fixed and this issue should be closed.

@supadrupa, the negativity in your second sentence is completely uncalled for. It's rude and counterproductive. Before you start getting nasty about other people's open source work, you should consider doing some of your own.

**Comment by supadrupa** [comment]
To begin with, they should write a proper code. And not write articles "BeDjango Starter" with awful solution.
And then that sort of developers, who read this article, go to work and write the same. And you have to waste a lot of time to explain them why this code is bad and why you shouldn't use it in your project. Thanks for this disease-breeder.

**Comment by axenedu** [comment]
If you don't like it then don't use it.

We are humans so we make mistakes, however, we only accept comments coming from people who are polite and constructive.

Thanks @pydanny !

**Comment by pydanny** [comment]
If I were you, I would block @supadrupa from all my repos and work. There's no reason to tolerate abusive, entitled behavior from someone who gives nothing back to the world. The same goes for @athene94, who just downvoted you. Block 'em both.

I have.

**Comment by iPablo** [comment]
Thanks @pydanny , They are blocked :)
